### ISSUE TITLE
bug of luaFunction.h

### ISSUE THREAD

**Issue by tangyu1018** [sniperHW/luawrapper#5]
//3参
Arg1 arg1 = GetRawValue<typename GetReplaceType<Arg1>::type>(tmp_arg1);
Arg2 arg2 = GetRawValue<typename GetReplaceType<Arg2>::type>(tmp_arg2);
Arg2 arg3 = GetRawValue<typename GetReplaceType<Arg3>::type>(tmp_arg3);

and also //4参

**Comment by sniperHW** [comment]
什么bug

**Comment by tangyu1018** [comment]
Arg2 arg3 = GetRawValue::type>(tmp_arg3);改成
Arg3 arg3 = GetRawValue::type>(tmp_arg3);

**Comment by sniperHW** [comment]
已经修正了
