### ISSUE TITLE
关于i64比较大小的问题

### ISSUE THREAD

**Issue by shuimu98** [sniperHW/luawrapper#6]
我看了下代码，关于i64支持那部分，有两个疑问：
1、在lua中创建i64,例如 `local a = i64.new(0,11)`，为什么要用两个参数，而且第一个参数好像在代码中并未使用；
2、比较两个i64的大小，在下面这种情况下会有问题：
    `local a=i64.new(0,11)
     local b =i64.new(0,a)
     print(a<=b)
   `
而其他情况都正常。

**Comment by sniperHW** [comment]
第一个问题很简单，你试试i64:new(11),将newI64中取第二个参数改为取第一个就可以i64.new(11)了。
第二个我不知道你那所谓的问题是什么
	local c=i64:new(11) 
	local d =i64:new(c) 
	print(c,d,c <= d) 
输出是11      11      true

**Comment by shuimu98** [comment]
第一个问题已经懂了，是我没有想到 i64:new() 这种 冒号的调用方式；
第二个问题：今天更新后，i64的new都改为`.`的方式调用了，但是还是会有问题，我直接上代码吧：
```
  local aa= i64.new(10)
  local bb = i64.new(aa) 
  print("################",aa,bb) 
  print("compare",aa<=bb)   
``` 

打印结果：
```
################        10      10
start.lua:14: attempt to compare two userdata values
-------call c function---------
lua中不存在函数test1
```

我修改了newI64 方法的实现：
把 `lua_pushlightuserdata(L,tmp); `替换成：

```
long initval = (long)tmp->GetValue();
size_t nbytes = sizeof(Integer64);
 void *buf = lua_newuserdata(L, nbytes);
new(buf)Integer64(initval);         
```                               
这样就OK了，不知道 lua_pushlightuserdata(L,tmp); 为什么会出问题。

**Comment by sniperHW** [comment]
这个错误应该是跟lua版本有关，我这里用5.3编译的没问题。应该改成你说的这样，否则aa bb实际指向同一个对象。

**Comment by shuimu98** [comment]
#define I64_RELA(OP)  最后的else是不是错了
```
i64self->m_val = i64self->m_val OP i64other->m_val;		\
lua_pushlightuserdata(L,i64self);	
```	

只用这样吧`lua_pushboolean(L,i64self->m_val OP i64other->m_val)`，
返回一个比较大小的结果就OK了，应该不用再push i64self了，否则出现
```
local a=i64.new(10)
local b=i64.new(a)
print(a>b)  --output true 这里结果错误
```

**Comment by sniperHW** [comment]
没错

**Comment by shuimu98** [comment]
好的，期待更新。
